#
# Makefile
#
#
# Makefile for Servlet PocoServer
#

include $(POCO_BASE)/build/rules/global

objects = CookieAdapter PocoHttpServletRequest PocoHttpServletResponse PocoServer

target         = PocoServer
target_version = 1
target_libs    = PocoFoundation PocoXML PocoUtil PocoNet Servlet ServletEx

include $(POCO_BASE)/build/rules/lib
