@echo off

rem
rem build_vs80.cmd
rem
rem command-line build script for VS 8 [generated by mkrelease]
rem

devenv /useenv /rebuild debug_shared Servlet_vs80.sln
devenv /useenv /rebuild release_shared Servlet_vs80.sln
