#
# Makefile
#
#
# Makefile for Servlet Servlet
#

include $(POCO_BASE)/build/rules/global

objects = Filter GenericServlet NoBodyResponse Object \
	PrintWriter BufferedReader RequestDispatcher Servlet \
	ServletConfig ServletContext ServletException \
	ServletInputStream ServletOutputStream \
	ServletRequest ServletRequestWrapper \
	ServletResponse ServletResponseWrapper \
	ServletStream UnavailableException \
	Cookie HttpServletRequest HttpServletResponse \
	HttpSession NoBodyResponse HttpServlet HttpServletRequestWrapper \
	HttpServletResponseWrapper HttpUtils


target         = Servlet
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
