#
# Makefile
#
#
# Makefile for Molto Portlet
#

include $(MOLTO_BASE)/build/rules/global

objects = RenderResponse PortletContext PreferencesValidator \
		UnavailableException GenericPortlet PortletModeException \
		PortletResponse PortletRequestDispatcher ReadOnlyException \
		Portlet WindowStateException PortletSessionUtil \
		PortletSecurityException RenderRequest PortletPreferences \
		ActionRequest PortalContext PortletRequest ValidatorException \
		PortletConfig PortletSession PortletMode PortletException \
		ActionResponse WindowState


target         = Portlet
target_version = 1
target_libs    = PocoFoundation

include $(MOLTO_BASE)/build/rules/lib
