#
# Makefile
#
# $Id: //poco/Main/Logging/testsuite/Makefile#1 $
#
# Makefile for Poco Logging testsuite
#

include $(POCO_BASE)/build/rules/global

objects = LoggingTestSuite Driver \
	<SourceFilesHere>

target         = testrunner
target_version = 1
target_libs    = PocoLogging PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
