echo off
rem Copyright (c) 2012, Applied Informatics Software Engineering GmbH.
rem and Contributors.

rem Permission is hereby granted, free of charge, to any person or organization
rem obtaining a copy of the software and accompanying documentation covered by
rem this license (the "Software") to use, reproduce, display, distribute,
rem execute, and transmit the Software, and to prepare derivative works of the
rem Software, and to permit third-parties to whom the Software is furnished to
rem do so, all subject to the following:

rem The copyright notices in the Software and this entire statement, including
rem the above license grant, this restriction and the following disclaimer,
rem must be included in all copies of the Software, in whole or in part, and
rem all derivative works of the Software, unless such copies or derivative
rem works are solely in the form of machine-executable object code generated by
rem a source language processor.

rem THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
rem IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
rem FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
rem SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
rem FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
rem ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
rem DEALINGS IN THE SOFTWARE.
echo on

premake4 gmake

pause

