#
# Makefile
#
# $Id: //poco/Main/template/library.make#3 $
#
# Makefile for Poco IO
#

include $(POCO_BASE)/build/rules/global

objects = ChannelStream NetConfig NetChannel Protocol ProtocolStream SerialConfig SerialChannel

target         = PocoIO
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
