#
# Makefile
#
# $Id: //poco/Main/template/library.make#3 $
#
# Makefile for Poco IO
#

include $(POCO_BASE)/build/rules/global

objects = AsyncCommand AsyncEvent AsyncChannel AsyncStreamChannel \
	Channel ChannelConfig ChannelStream \
	Protocol ProtocolStream

target         = PocoIO
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
