#
# Makefile
#
# $Id: //poco/Main/Foundation/testsuite/Makefile-Driver#14 $
#
# Makefile for Molto - the servlet container application
#

include $(POCO_BASE)/build/rules/global

objects = Molto main

target         = Molto
target_version = 1
target_libs    = PocoFoundation PocoXML PocoUtil Servlet ServletEx Container

include $(POCO_BASE)/build/rules/exec
