#
# Makefile
#
# $Id: //poco/Main/Logging/Makefile#2 $
#
# Makefile for Poco Logging
#

include $(POCO_BASE)/build/rules/global

objects = AbstractFilter PriorityFilter RepetitionFilter TextFilter \
	ParamFilter RegExpFilter SourceFilter

target         = PocoLogging
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
