//
// SSHException.cpp
//
// $Id: //poco/Main/SSH/src/SSHException.cpp#1 $
//
// Library: SSH
// Package: SSHCore
// Module:  SSHException
//
// Copyright (c) 2007, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#include "Poco/SSH/SSHException.h"
#include <typeinfo>


using Poco::Net::NetException;


namespace Poco {
namespace SSH {


POCO_IMPLEMENT_EXCEPTION(SSHException, NetException, "SSH Exception")
POCO_IMPLEMENT_EXCEPTION(SSHAuthException, SSHException, "SSH Auth Exception")
POCO_IMPLEMENT_EXCEPTION(SCPException, SSHException, "SCP Exception")
POCO_IMPLEMENT_EXCEPTION(SSHNotImplementedException, SSHException, "SSH not implemented Exception")
POCO_IMPLEMENT_EXCEPTION(SSHNotSupportedException, SSHException, "SSH not supported Exception")


} } // namespace Poco::SSH
