//
// SSHSubSystem.cpp
//
// $Id: //poco/Main/SSH/src/SSHSubSystem.cpp#1 $
//
// Library: SSH
// Package: SSHTerminal
// Module:  SSHSubSystem
//
// Copyright (c) 2007, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#include "Poco/SSH/SSHSubSystem.h"
#include "Poco/SSH/SSHSession.h"
#include "Poco/SSH/SSHException.h"
#include "libssh2.h"


namespace Poco {
namespace SSH {


SSHSubSystem::SSHSubSystem():
	_pSession(0),
	_channel()
{
}


SSHSubSystem::SSHSubSystem(SSHSession& session):
	_pSession(0),
	_channel()
{
	init(session);
}


SSHSubSystem::~SSHSubSystem()
{
	close();
}


void SSHSubSystem::init(SSHSession& session)
{
	close();
	_channel.init(session);
	_pSession = &session;
	_pSession->duplicate();
}


void SSHSubSystem::close()
{
	_channel.close();

	if (_pSession)
		_pSession->release();
	_pSession = 0;
}


SSHChannel SSHSubSystem::request(const std::string& subSystemName)
{
	if (!_channel.channel())
		throw SSHException("SSHSubSystem not initialized");

	if (libssh2_channel_subsystem(_channel.channel(), subSystemName.c_str()))
	{
		throw SSHException("Failed to invoke subsystem for SSHTerminal");
	}
	return _channel;
}


} } // namespace Poco::SSH
