//
// SourceFilter.h
//
// $Id: //poco/1.3/Logging/include/Poco/Logging/SourceFilter.h#2 $
//
// Library: Logging
// Package: Filters
// Module:  SourceFilter
//
// Definition of the SourceFilter class.
//
// Copyright (c) 2006-2009, Applied Informatics Software Engineering GmbH.
// All rights reserved.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#ifndef Logging_SourceFilter_INCLUDED
#define Logging_SourceFilter_INCLUDED


#include "Poco/Logging/Logging.h"
#include "Poco/Logging/RegExpFilter.h"


namespace Poco {
namespace Logging {


class Logging_API SourceFilter: public RegExpFilter
	/// A filter that matches the message's source agains a regular expression.
{
public:
	SourceFilter();
		/// Creates the SourceFilter.

	SourceFilter(const std::string& expr);
		/// Creates the SourceFilter with the given regular expression.

	SourceFilter(const std::string& expr, int options);
		/// Creates the SourceFilter with the given regular expression and
		/// options. 
		/// See the Poco::RegularExpression class for a list of
		/// valid options.

	~SourceFilter();
		/// Destroys the SourceFilter.

	void log(const Poco::Message& msg);
		/// Passes the message on to the next channel,
		/// its source matches the regular expression.

	static void registerChannel();
		/// Registers the channel with the global LoggingFactory.
};


} } // namespace Poco::Logging


#endif // Logging_SourceFilter_INCLUDED
