#
# Makefile
#
# $Id: //poco/Main/template/library.make#3 $
#
# Makefile for Poco Serial
#

include $(POCO_BASE)/build/rules/global

objects = SerialConfig SerialChannel

target         = PocoSerial
target_version = $(LIBVERSION)
target_libs    = PocoFoundation PocoDeviceIO

include $(POCO_BASE)/build/rules/lib
