//
// TestSuite.cpp
//
// $Id: //poco/1.3/Foundation/testsuite/src/SharedArrayTest.cpp#1 $
//
// Copyright (c) 2004-2006, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#include "TestSuite.h"

#include <Poco/SharedArray.h>
#include <Poco/Mutex.h>

#include <assert.h>
#include <iostream>
#include <vector>

using Poco::SharedArray;
using Poco::NullPointerException;

namespace
{
    class TestObject
    {
    public:
        TestObject(const int& data = 0) : _data(data)
        {
            Poco::FastMutex::ScopedLock lock(_mutex);
            ++_count;
            std::cout << "current counter : " << _count << "\n";
        }

        virtual ~TestObject()
        {
            Poco::FastMutex::ScopedLock lock(_mutex);
            --_count;
            std::cout << "current counter : " << _count << "\n";
        }

        void set(const int& data)
        {
            _data = data;
        }

        int& data()
        {
            return _data;
        }

        static int count()
        {
            return _count;
        }

    private:
        int _data;
        static int _count;

        Poco::FastMutex _mutex;
    };

    int TestObject::_count = 0;
}

void SharedArrayTestSuite::testConstruction()
{

    {
        // default construction
        SharedArray<TestObject> ptr1;
        poco_assert(ptr1.get() == 0);

        try
        {
            poco_assert (ptr1[0].data() == 1);
            assert (!"must throw NullPointerException");
        }
        catch (NullPointerException& e)
        {
            std::cout << "Exception caught: " << e.displayText() << std::endl;
        }

    }

    poco_assert(TestObject::count() == 0);

    // construct from explicit raw pointer to dynamical allocated array
    {        
        SharedArray<TestObject> ptr2(new TestObject[10]);
        poco_assert(ptr2.get() != 0);
        poco_assert(ptr2);
        poco_assert(!ptr2 == false);
        poco_assert(TestObject::count() == 10);

        // the following code wont compile
        TestObject* p = new TestObject[10];
        SharedArray<TestObject> ptr3(p);
    }

    poco_assert(TestObject::count() == 0);

    // copy construction 
    {        
        SharedArray<TestObject> ptr3(new TestObject[10]);
        poco_assert(ptr3.get() != 0);
        poco_assert(TestObject::count() == 10);

        SharedArray<TestObject> ptr4(ptr3);
        poco_assert(TestObject::count() == 10);
    }
    poco_assert(TestObject::count() == 0);

}

void SharedArrayTestSuite::testAssignment()
{
    poco_assert(TestObject::count() == 0);

    {
        
        SharedArray<TestObject> ptr1(new TestObject[10]);
        poco_assert(ptr1.get() != 0);
        poco_assert(TestObject::count() == 10);

        SharedArray<TestObject> ptr2 = ptr1;

        poco_assert(TestObject::count() == 10);

    }

    poco_assert(TestObject::count() == 0);

    // note we use explicit constructor for raw pointer, the following wont compile
    // {        
    //    TestObject*p = new TestObject[10];        
    //    SharedArray<TestObject> ptr1 = p;
    // }


}

void SharedArrayTestSuite::testSwap()
{
    poco_assert(TestObject::count() == 0);

    {
        
        SharedArray<TestObject> ptr1(new TestObject[10]);

        // before swap
        poco_assert(ptr1.get() != 0);
        poco_assert(TestObject::count() == 10);

        {
            SharedArray<TestObject> ptr2(new TestObject[20]);
            ptr2.swap(ptr1);
            poco_assert(TestObject::count() == 30);     
            poco_assert(ptr2.get() != 0);
        }

        // after swap
        poco_assert(ptr1.get() != 0);
        poco_assert(TestObject::count() == 20);

    }

    poco_assert(TestObject::count() == 0);

}

void SharedArrayTestSuite::testElementAccess()
{
    poco_assert(TestObject::count() == 0);

    {
        
        SharedArray<TestObject> ptr1(new TestObject[10]);

        for(int i = 0; i<10; i++){
            ptr1[i].set(i);
        }

        for(int i = 0; i<10; i++){
            poco_assert(i == ptr1[i].data());
        }        

    }

    poco_assert(TestObject::count() == 0);

}


void SharedArrayTestSuite::testAddressComparison()
{
    poco_assert(TestObject::count() == 0);

    {
        
        SharedArray<TestObject> ptr1(new TestObject[10]);
        SharedArray<TestObject> ptr2(new TestObject[10]);
        SharedArray<TestObject> ptr3(ptr1);

        poco_assert(ptr1);
        poco_assert(ptr2 != ptr1);
        poco_assert(ptr3 == ptr1);

        if(ptr1.get() > ptr2.get()){
           poco_assert(ptr1 > ptr2);
        }
        if(ptr1.get() >= ptr2.get()){
            poco_assert(ptr1 >= ptr2);
        }
        if(ptr1.get() < ptr2.get()){
            poco_assert(ptr1 < ptr2);
        }
        if(ptr1.get() <= ptr2.get()){
            poco_assert(ptr1 <= ptr2);
        }


    }

    poco_assert(TestObject::count() == 0);

}

void SharedArrayTestSuite::testStlContainers()
{
    poco_assert(TestObject::count() == 0);

    {
        
        typedef std::vector<SharedArray<TestObject> >             TContainer;
        typedef std::vector<SharedArray<TestObject> >::iterator   TIter;

        TContainer container;

        container.push_back(SharedArray<TestObject> (new TestObject[10]));
        container.push_back(SharedArray<TestObject> (new TestObject[10]));
        container.push_back(SharedArray<TestObject> (new TestObject[10]));           

        poco_assert(TestObject::count() == 30);

        for(TIter it = container.begin(); it != container.end(); ++it){
            (*it)[0].set(0);
        }

        poco_assert(container[0][0].data() == 0);
        poco_assert(container[1][0].data() == 0);
        poco_assert(container[2][0].data() == 0);

    }

    poco_assert(TestObject::count() == 0);

}

int main()
{

    SharedArrayTestSuite test;

    test.testConstruction();
    test.testAssignment();
    test.testSwap();
    test.testElementAccess();
    test.testAddressComparison();
    test.testStlContainers();
}
