#
# Makefile
#
# $Id: //poco/Main/Script/Makefile#2 $
#
# Makefile for Poco Script
#

include $(POCO_BASE)/build/rules/global

objects = Environment ScriptException \
	EnvironmentStream EnvironmentStreamBuf

target         = PocoScript
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
