#
# Makefile
#
# $Id: //poco/Script/Lua/testsuite/Makefile#2 $
#
# Makefile for Poco Lua testsuite
#

include $(POCO_BASE)/build/rules/global

objects = LuaTestSuite Driver LuaTest

target         = testrunner
target_version = 1
target_libs    = PocoLua PocoScript PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
