#
# Makefile
#
# $Id: //poco/Main/template/library.make#3 $
#
# Makefile for Poco Serial
#

include $(POCO_BASE)/build/rules/global

objects = SocketChannel AsyncSocketChannel

target         = PocoSocket
target_version = $(LIBVERSION)
target_libs    = PocoFoundation PocoDeviceIO PocoNet

include $(POCO_BASE)/build/rules/lib
