#
# Makefile
#
# $Id: //poco/Main/Logging/Server/Makefile#1 $
#
# Makefile for Poco LoggingServer
#

include $(POCO_BASE)/build/rules/global

objects = CachingChannel DatabaseChannel DataRetriever LoggingHandler LoggingServer

target         = LoggingServer
target_version = 1
target_libs    = PocoLogging PocoSQLite PocoODBC PocoData PocoNetSSL PocoNet PocoUtil PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
