//
// TestFilter.h
//
//
// Library: TestFilter
// Package: TestFilter
// Module:  TestFilter
//
// Definition of the TestFilter class.
//
// Copyright (c) 2006, Aleksandar Fabijanic and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#ifndef Servlet_TestFilter_INCLUDED
#define Servlet_TestFilter_INCLUDED


#include "Poco/Servlet/Filter.h"
#include "Poco/Servlet/HttpServletRequestWrapper.h"
#include "Poco/Servlet/HttpServletResponseWrapper.h"
#include <sstream>


#if defined(_WIN32) && defined(POCO_SERVLET_DLL)
#	if defined(FILTERTEST_EXPORTS)
#		define CPP_FILTERTEST_DLL_API __declspec(dllexport)
#	else
#		define CPP_FILTERTEST_DLL_API __declspec(dllimport)
#	endif
#else
#	define CPP_FILTERTEST_DLL_API 
#endif


namespace Poco {
namespace Servlet {


class FilteredRequest : public HttpServletRequestWrapper
{
public:
	FilteredRequest(HttpServletRequest& request);
	ServletInputStream& getInputStream();
	const BufferedReader& getReader() const;

private:
	std::istringstream _istream;
	mutable ServletInputStream _servletInputStream;
	BufferedReader _reader;
};


class FilteredResponse : public HttpServletResponseWrapper
{
public:
	FilteredResponse(HttpServletResponse& response);
	ServletOutputStream& getOutputStream();
	PrintWriter& getWriter();
	const std::string toString();

private:
	std::ostringstream  _ostream;
	ServletOutputStream _servletOutputStream;
	PrintWriter         _writer;
};


class CPP_FILTERTEST_DLL_API TestFilter : public Filter
{
public: 
	TestFilter();
	~TestFilter();

	void init(const FilterConfig& filterConfig);
	void doFilter(ServletRequest& request
		, ServletResponse& response
		, const FilterChain* chain) const;
	void destroy();
};


} } // namespace Poco::Servlet


#endif //Servlet_TestFilter_INCLUDED
