#
# Makefile
#
# $Id: //poco/Main/SSH/testsuite/Makefile#1 $
#
# Makefile for Poco SSH testsuite
#

include $(POCO_BASE)/build/rules/global

objects = SSHTestSuite Driver \
	SSHTest

target         = testrunner
target_version = 1
target_libs    = PocoSSH PocoNet PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
