#
# Makefile
#
# $Id: //poco/Main/Script/testsuite/Makefile#2 $
#
# Makefile for Poco Script testsuite
#

include $(POCO_BASE)/build/rules/global

objects = ScriptTestSuite Driver ScriptTest \

target         = testrunner
target_version = 1
target_libs    = PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
